name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - name: test
        run: file modules.tar


